# Generated by Django 4.2.28 on 2026-02-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="display_name",
            field=models.CharField(default="Jyati", max_length=50),
        ),
    ]
