# Generated by Django 4.2.28 on 2026-02-10 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_alter_userprofile_display_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("notes_created", models.IntegerField(default=0)),
                ("notes_edited", models.IntegerField(default=0)),
                ("diary_entries", models.IntegerField(default=0)),
                ("goals_created", models.IntegerField(default=0)),
                ("tasks_completed", models.IntegerField(default=0)),
                ("ai_chats", models.IntegerField(default=0)),
                ("login_count", models.IntegerField(default=0)),
                ("total_time_minutes", models.IntegerField(default=0)),
                ("first_activity", models.DateTimeField(blank=True, null=True)),
                ("last_activity", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Daily Activities",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
