# Generated by Django 4.2.28 on 2026-03-02 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_usersession"),
    ]

    operations = []
