# Generated by Django 4.2.28 on 2026-02-07 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiaryPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=300)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("self_awareness", "Self-Awareness"),
                            ("relationships", "Relationships"),
                            ("professional", "Professional Growth"),
                            ("gratitude", "Gratitude"),
                            ("challenges", "Challenge Processing"),
                            ("general", "General"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Diary Prompts",
            },
        ),
        migrations.CreateModel(
            name="MoodSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField()),
                ("avg_mood", models.FloatField()),
                ("entry_count", models.IntegerField()),
                ("dominant_theme", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mood_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Mood Summaries",
                "unique_together": {("user", "week_start")},
            },
        ),
        migrations.CreateModel(
            name="DiaryEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("entry_date", models.DateField()),
                ("content", models.TextField(blank=True)),
                ("content_html", models.TextField(blank=True)),
                (
                    "input_method",
                    models.CharField(
                        choices=[
                            ("type", "Typing"),
                            ("voice", "Voice"),
                            ("stylus", "Stylus/Handwriting"),
                        ],
                        default="type",
                        max_length=10,
                    ),
                ),
                ("voice_transcript", models.TextField(blank=True)),
                ("voice_duration", models.IntegerField(blank=True, null=True)),
                ("handwriting_strokes", models.JSONField(blank=True, null=True)),
                ("handwriting_ocr_text", models.TextField(blank=True)),
                (
                    "handwriting_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="diary/handwriting/"
                    ),
                ),
                (
                    "mood",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "😔 Struggling"),
                            (2, "😕 Difficult"),
                            (3, "😐 Neutral"),
                            (4, "🙂 Good"),
                            (5, "😊 Great"),
                        ],
                        null=True,
                    ),
                ),
                ("mood_note", models.CharField(blank=True, max_length=200)),
                ("prompt_used", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diary_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Diary Entries",
                "ordering": ["-entry_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "-entry_date"],
                        name="diary_diary_user_id_3e0a8b_idx",
                    )
                ],
                "unique_together": {("user", "entry_date")},
            },
        ),
    ]
