# Generated by Django 4.2.28 on 2026-04-18 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TangredProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("stitch_project_id", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tangred_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-modified_at"],
            },
        ),
        migrations.CreateModel(
            name="TangredScreen",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("prompt", models.TextField()),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("MOBILE", "Mobile"),
                            ("DESKTOP", "Desktop"),
                            ("TABLET", "Tablet"),
                            ("AGNOSTIC", "Agnostic"),
                        ],
                        default="MOBILE",
                        max_length=20,
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        choices=[
                            ("GEMINI_3_FLASH", "Gemini 3 Flash"),
                            ("GEMINI_3_1_PRO", "Gemini 3.1 Pro"),
                        ],
                        default="GEMINI_3_FLASH",
                        max_length=30,
                    ),
                ),
                ("stitch_session_id", models.CharField(blank=True, max_length=64)),
                ("stitch_screen_name", models.CharField(blank=True, max_length=255)),
                ("stitch_screen_id", models.CharField(blank=True, max_length=64)),
                ("screenshot_url", models.URLField(blank=True)),
                ("html_url", models.URLField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("suggestions", models.JSONField(blank=True, default=list)),
                ("status", models.CharField(default="UNKNOWN", max_length=32)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screens",
                        to="tangred.tangredproject",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
