# Generated by Django 4.2.28 on 2026-04-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tangred", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tangredscreen",
            name="optimized_prompt",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tangredscreen",
            name="prompt_optimizer_model",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="tangredscreen",
            name="prompt_optimizer_provider",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
