# Generated by Django 4.2.28 on 2026-04-18 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tangred", "0002_tanstudio_prompt_optimizer_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="TangredSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("occasion", models.CharField(blank=True, max_length=120)),
                ("body_frame", models.CharField(blank=True, max_length=120)),
                ("skin_tone", models.CharField(blank=True, max_length=120)),
                ("preferred_palette", models.CharField(blank=True, max_length=255)),
                ("avoid_palette", models.CharField(blank=True, max_length=255)),
                ("style_goal", models.TextField(blank=True)),
                ("wardrobe_notes", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("PROCESSING", "Processing"), ("READY", "Ready"), ("ERROR", "Error")], default="DRAFT", max_length=16)),
                ("style_identity", models.CharField(blank=True, max_length=255)),
                ("body_summary", models.TextField(blank=True)),
                ("outfit_direction", models.TextField(blank=True)),
                ("wardrobe_blueprint", models.JSONField(blank=True, default=list)),
                ("accessory_focus", models.TextField(blank=True)),
                ("color_story", models.TextField(blank=True)),
                ("confidence_notes", models.TextField(blank=True)),
                ("visualization_prompt", models.TextField(blank=True)),
                ("openrouter_provider", models.CharField(blank=True, max_length=50)),
                ("openrouter_model", models.CharField(blank=True, max_length=100)),
                ("raw_agent_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("styleboard_project", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="agent_sessions", to="tangred.tangredproject")),
                ("styleboard_screen", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="agent_sessions", to="tangred.tangredscreen")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tangred_sessions", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-modified_at"]},
        ),
        migrations.CreateModel(
            name="TangredSessionPhoto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="tangred/sessions/")),
                ("caption", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="photos", to="tangred.tangredsession")),
            ],
            options={"ordering": ["created_at"]},
        ),
    ]
