# Generated by Django 4.2.28 on 2026-04-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tangred", "0003_tangredsession_tangredsessionphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="tangredsessionphoto",
            name="content_type",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="tangredsessionphoto",
            name="original_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="tangredsessionphoto",
            name="size_bytes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tangredsessionphoto",
            name="storage_backend",
            field=models.CharField(choices=[("local", "Local"), ("firebase", "Firebase Storage")], default="local", max_length=20),
        ),
        migrations.AddField(
            model_name="tangredsessionphoto",
            name="storage_path",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="tangredsessionphoto",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="tangred/sessions/"),
        ),
    ]
