# Generated by Django 4.2.28 on 2026-04-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tangred", "0004_tangredsessionphoto_private_storage_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="tangredsessionphoto",
            name="binary_content",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tangredsessionphoto",
            name="storage_backend",
            field=models.CharField(choices=[("local", "Local"), ("database", "Database"), ("firebase", "Firebase Storage")], default="database", max_length=20),
        ),
    ]
